### ISSUE TITLE
[Boring] Licensing: why not AGPLv3?

### ISSUE THREAD

**Issue by hugoroy** [dellsystem/wikinotes#182]
Hello,

I'm curious: why the choice of GPLv3 over AGPLv3? This license is exactly aims at programs like wikinotes that are hosted and accessed through a network by users. The license is up at http://www.gnu.org/licenses/agpl.html It's exactly the same as GPLv3, except for clause `13. Remote Network Interaction; Use with the GNU General Public License.’

[my former university is heading towards all-Google. I'm really disappointed to see that, I'm curious if they'd be interested in wikinotes…]

**Comment by dellsystem** [comment]
Hi Hugo! Thanks for bringing this up. I went with the GPL because it was the license I was most familiar with when I started the project. You are right that the AGPL would be more appropriate for Wikinotes. I'm not too worried about licensing issues right now, so I'm going to close this for now, but perhaps I'll revisit this issue in the future.

**Comment by hugoroy** [comment]
It’s entirely up to you of course. But in these matters, the
sooner the better: you’ll need agreement from all copyright
holders.

Now I’ll just stop my AGPL advocating ☺

Thanks,
Hugo
