### ISSUE TITLE
Generate PDF

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#82]
It should be possible to do this on a per-page level as well as on a per-course level (with, of course, the ability to select the pages to include). Generated server-side and served for download each time. Probably doesn't need caching, but think about it.

**Comment by hc5** [comment]
I want to get this done since a few of my friends asked for a printable version of the notes, and the straight up webpage print was kinda bad. A couple issues need to think about though:
- mathjax equations, this means we can't do a straight up html->pdf conversion. makes sense that we do html->latex->pdf, if so, we have to decide on when we compile the latex, since it's fairly time/resource consuming. caching would be a must.
- link to offsite images. if we have a cached pdf of a copyrighted image, it might be considered as hosting copyright content on our server. also, if we download the images to a tmp directory to compile the latex, those images would be on our server as well. 

there are probably a few other issues, but these are the big ones that i can think of

**Comment by dellsystem** [comment]
Closing, since the print view makes this redundant. The per-course-level idea should be incorporated into series somehow.
